//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lib_gfx.rc
//

#define IDR_SHADER_VERTEX_BLEND         1102
#define IDR_SHADER_SKY_BLEND            1103
#define IDR_SHADER_TERRAIN_BLEND        1104
#define IDR_SHADER_VERTEX_BLEND_EX      1105
#define IDR_SHADER_SHADOW_VOLUME		1106
#define IDR_SHADER_GEOMETRY_LINE_FLAKE  1107
#define IDR_SHADER_GEOMETRY_LINE_VOLUME 1108
#define IDR_SHADER_PP_COMBINE			1109
#define IDR_SHADER_PP_COMBINE_4X		1110
#define IDR_SHADER_PP_COMBINE_HDR		1111
#define IDR_SHADER_PP_COMBINE_DOF		1113
#define IDR_SHADER_PP_COLOR_TONE_MAP	1114
#define IDR_SHADER_PP_DOWN_FILTER_4X	1115
#define IDR_SHADER_PP_GAUSSIAN_BLUR_H	1116
#define IDR_SHADER_PP_GAUSSIAN_BLUR_V	1117
#define IDR_SHADER_PP_UP_FILTER_4X		1118
#define IDR_SHADER_PP_COMBINE_HSL		1119
#define IDR_SHADER_COMMON_MESH			1120
#define IDR_SHADER_REFLECTION			1121
#define IDR_SHADER_FLOW_DIRECTION		1122
#define IDR_SHADER_FLOOD_ANALYSIS		1123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
